### ISSUE TITLE
NoSuchMethodError in GlintTypeScriptService.getServer() on IntelliJ IDEA 2026.1 (build 261)

### ISSUE THREAD

**Issue by Timur-IQ** [patricklx/intellij-emberjs-experimental#387]
**Title:** NoSuchMethodError in GlintTypeScriptService.getServer() on IntelliJ IDEA 2026.1 (build 261)

---

### Environment

| | |
|---|---|
| IDE | IntelliJ IDEA Ultimate 2026.1, build `IU-261.26222.65` |
| Plugin | Ember.js (experimental) `com.emberjs.experimental` 2025.3.1 |
| OS | Windows 11 |
| Project | Ember 3.28 app, plain JavaScript — no TypeScript, no `.gts`/`.gjs` files, no glint config, `@glint/core` not installed |

### What happens

After updating the IDE from 2025.x to 2026.1, editing any `.hbs` file raises a repeating IDE internal error. Highlighting in Handlebars files is dead as a result.

```
com.intellij.diagnostic.PluginException: annotator: com.emberjs.gts.HbLintExternalAnnotator@1c0c59d
  (class com.emberjs.gts.HbLintExternalAnnotator) [Plugin: com.emberjs.experimental]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:298)
Caused by: java.lang.NoSuchMethodError: 'com.intellij.platform.lsp.impl.LspServerImpl com.emberjs.glint.GlintTypeScriptService.getServer()'
    at com.emberjs.glint.GlintTypeScriptService.highlight(GlintLanguageService.kt:176)
    at com.emberjs.gts.HbLintExternalAnnotator.doAnnotate(HbLinter.kt:127)
    at com.emberjs.gts.HbLintExternalAnnotator.doAnnotate(HbLinter.kt:107)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.lambda$doAnnotate$1(ExternalToolPass.java:248)
    at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:91)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:246)
```

### Steps to reproduce

1. Install plugin 2025.3.1 on IDEA 2026.1 (`IU-261.26222.65`).
2. Open an Ember project — no Glint setup required, see note below.
3. Open and edit a `.hbs` file.
4. The internal error appears and repeats on every re-highlight.

### Analysis

The signature in the error message references `com.intellij.platform.lsp.impl.LspServerImpl` as the return type of `getServer()`. That method is inherited from the platform's LSP base class, whose return type appears to have changed in 261 — so the call site compiled against the 2025.3 platform no longer resolves. Plugin 2025.3.1 declares:

```xml
<idea-version since-build="253.28294" />
```

With no `until-build`, the IDE loads the plugin on 261 without any compatibility warning, and the incompatibility only surfaces at runtime.

### Two separate points

1. **Binary incompatibility with 261** — a build against the 2026.1 platform is needed. Until that exists, an `until-build` bound would at least make the IDE flag the plugin instead of silently loading it.

2. **The annotator runs even when Glint is not set up at all.** In this project there is no TypeScript, no `.gts` file, no glint config and no `@glint/core` in `node_modules`; the settings page (Settings → Ember.js → Glint) has *Glint package* and *Node interpreter* empty. `HbLintExternalAnnotator` still calls into `GlintTypeScriptService`. A guard that skips the annotator when no Glint package is resolved would make the plugin usable for plain-JS Ember projects, and would have contained this crash.

### Workaround

Disabling the plugin. There is no setting that turns the Glint integration off: the Glint settings page only offers the package/interpreter fields, and the "Glint" inspection that can be disabled applies to `Gts` files only, not to the Handlebars external annotator.
